<?php
/**
 * ViraXpress - https://www.viraxpress.com
 *
 * LICENSE AGREEMENT
 *
 * This file is part of the ViraXpress package and is licensed under the ViraXpress license agreement.
 * You can view the full license at:
 * https://www.viraxpress.com/license
 *
 * By utilizing this file, you agree to comply with the terms outlined in the ViraXpress license.
 *
 * DISCLAIMER
 *
 * Modifications to this file are discouraged to ensure seamless upgrades and compatibility with future releases.
 *
 * @author      ViraXpress
 * @copyright   © 2024 ViraXpress (https://www.viraxpress.com/)
 * @license     https://www.viraxpress.com/license
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block
 * @var \Magento\Framework\Locale\LocaleFormatter $localeFormatter
 */
 $availableLimitOptions = $block->getAvailableLimit();
?>
<?php if (count($availableLimitOptions) > 1): ?>
    <div class="field limiter flex items-center order-3 sm:order-2 md:order-3 lg:order-2 col-span-2 justify-end">
        <div class="control">
            <label class="text-sm label">
                <span aria-hidden="true"><?= $escaper->escapeHtml((string)__('Show')) ?></span>

                <select
                    data-role="limiter"
                    class="form-select limiter-options"
                    @change="changeUrl(
                        'product_list_limit',
                        $event.currentTarget.options[$event.currentTarget.selectedIndex].value,
                        options.limitDefault
                    )"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Show items per page')) ?>"
                >
                <?php foreach ($block->getAvailableLimit() as $key => $limit): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($key) ?>"
                        <?php if ($block->isLimitCurrent($key)): ?>
                            selected="selected"
                        <?php endif ?>>
                        <?= $escaper->escapeHtml(is_numeric($limit) ? $localeFormatter->formatNumber((int) $limit) : $limit) ?>
                    </option>
                <?php endforeach; ?>
                </select>
            </label>
        </div>
    </div>
<?php else: ?>
    <div class="field limiter flex order-3 sm:order-2 md:order-3 lg:order-2 col-span-2 justify-end">

    </div>
<?php endif;
